spring.application.name=scheduler
spring.autoconfigure.exclude=org.optaplanner.spring.boot.autoconfigure.OptaPlannerAutoConfiguration

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
